apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
  - name: regcreds
  containers:
  - name: shell
    image: linux-cli:jdk11-0.1.0
    command:
    - sleep
    args:
    - infinity
    resources:
      requests:
        memory: 4Gi
        cpu: 2      
      limits:
        memory: 4Gi
        cpu: 2
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: docker-daemon
    image: docker:19.03.1-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""